name: esas_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.5.0

dependencies: 
  cupertino_icons: ^1.0.8
  get: 4.6.6
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  geolocator: ^13.0.1
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  path_provider: ^2.1.4
  path: ^1.9.0
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  card_loading: ^0.3.2
  u_credit_card: ^1.3.1
  http: ^1.2.2
  socket_io_client: ^3.0.0
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1
  flutter_widget_from_html: ^0.15.2

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  fonts:
    - family: JakartaSans
      fonts:
        - asset: assets/font/PlusJakartaSans-Italic.ttf
          weight: 400
        - asset: assets/font/PlusJakartaSans.ttf
          weight: 700
  uses-material-design: true
  assets:
    - assets/images/introductions/
    - assets/images/apps/
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/lottie/
    - assets/